// Concatenates sql/NN_*.sql (in order) into sql/00_ALL.sql, so the whole
// schema can be pasted into Supabase > SQL Editor in one go.
// Every file is idempotent, so running 00_ALL.sql again is safe.
// Usage: npm run sql:all
import fs from "node:fs";
import path from "node:path";

const dir = path.join(path.dirname(new URL(import.meta.url).pathname), "..", "sql");
const files = fs
  .readdirSync(dir)
  .filter((f) => /^\d\d_.+\.sql$/.test(f) && f !== "00_ALL.sql")
  .sort();

const parts = files.map((f) => `-- ===========================================================================\n-- ${f}\n-- ===========================================================================\n\n${fs.readFileSync(path.join(dir, f), "utf8").trimEnd()}\n`);
const header = `-- GENERATED by \`npm run sql:all\` — do not edit; edit the numbered files instead.\n-- Contains, in order: ${files.join(", ")}\n-- Safe to re-run.\n\n`;
fs.writeFileSync(path.join(dir, "00_ALL.sql"), header + parts.join("\n"));
console.log(`sql/00_ALL.sql ← ${files.length} files`);
