-- GENERATED by `npm run sql:all` — do not edit; edit the numbered files instead.
-- Contains, in order: 00_books.sql, 01_admin_role.sql, 02_page_comments.sql, 03_book_print_settings.sql, 04_book_shares.sql, 05_usage_and_templates.sql
-- Safe to re-run.

-- ===========================================================================
-- 00_books.sql
-- ===========================================================================

-- The base table: one row per book, every page in `pages` (jsonb array).
--
-- This is the schema the app was set up with; on an existing project it
-- changes nothing (same table, same policy names). On a NEW Supabase
-- project it must run first — everything in 01–05 builds on public.books.
-- Run once in Supabase > SQL Editor. Safe to re-run.

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  pages jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published')),
  collection text,
  trim_size text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_user_id_idx on public.books (user_id);

alter table public.books enable row level security;

-- Each user sees and changes only their own books. (Supervisors get extra
-- read/delete access in 01_admin_role.sql.) The update policy has no
-- separate WITH CHECK, so Postgres applies the USING condition to the new
-- row too: nobody can hand a book to another user_id.
drop policy if exists "select own books" on public.books;
create policy "select own books" on public.books for select using (auth.uid() = user_id);

drop policy if exists "insert own books" on public.books;
create policy "insert own books" on public.books for insert with check (auth.uid() = user_id);

drop policy if exists "update own books" on public.books;
create policy "update own books" on public.books for update using (auth.uid() = user_id);

drop policy if exists "delete own books" on public.books;
create policy "delete own books" on public.books for delete using (auth.uid() = user_id);

-- ===========================================================================
-- 01_admin_role.sql
-- ===========================================================================

-- Supervisor / admin role.
--
-- Admins can READ and DELETE every user's books and list all accounts
-- (the /studio/admin page). They deliberately can't UPDATE other users'
-- books: saveBook() upserts with the *current* user's id, so an admin
-- editing someone else's book would silently take ownership of it.
--
-- Run once in Supabase > SQL Editor. Safe to re-run.

-- Who is an admin. RLS on with no policies: the table is invisible to the
-- client; only the SECURITY DEFINER functions below read it.
create table if not exists public.app_admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.app_admins enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.app_admins where user_id = auth.uid());
$$;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- Additive to the existing "own rows only" policies on books.
drop policy if exists "Admins can read all books" on public.books;
create policy "Admins can read all books" on public.books
  for select to authenticated
  using ((select public.is_admin()));

drop policy if exists "Admins can delete any book" on public.books;
create policy "Admins can delete any book" on public.books
  for delete to authenticated
  using ((select public.is_admin()));

-- auth.users isn't exposed through the API, so the user list goes through
-- this function, which refuses anyone who isn't an admin.
-- (sql/05_usage_and_templates.sql redefines it with AI-usage
-- columns — run that one again after re-running this file.)
drop function if exists public.admin_list_users();
create function public.admin_list_users()
returns table (
  id uuid,
  email text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  email_confirmed_at timestamptz,
  is_admin boolean,
  book_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  return query
    select
      u.id,
      u.email::text,
      u.created_at,
      u.last_sign_in_at,
      u.email_confirmed_at,
      exists (select 1 from public.app_admins a where a.user_id = u.id),
      (select count(*) from public.books b where b.user_id = u.id)
    from auth.users u
    order by u.created_at desc;
end;
$$;
revoke all on function public.admin_list_users() from public, anon;
grant execute on function public.admin_list_users() to authenticated;

-- Promote/demote another account from the admin page. A supervisor can't
-- demote themselves, so the app can never end up with nobody able to
-- manage it.
create or replace function public.admin_set_supervisor(target_user uuid, make_supervisor boolean)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if target_user = auth.uid() and not make_supervisor then
    raise exception 'You can''t remove your own supervisor access.' using errcode = '42501';
  end if;

  if make_supervisor then
    insert into public.app_admins (user_id) values (target_user) on conflict do nothing;
  else
    delete from public.app_admins where user_id = target_user;
  end if;
end;
$$;
revoke all on function public.admin_set_supervisor(uuid, boolean) from public, anon;
grant execute on function public.admin_set_supervisor(uuid, boolean) to authenticated;

-- Make the FIRST supervisor (create the account under Authentication > Users);
-- after that, supervisors can promote others from /studio/admin:
--   insert into public.app_admins (user_id)
--   select id from auth.users where email = 'supervisor@example.com'
--   on conflict do nothing;

-- ===========================================================================
-- 02_page_comments.sql
-- ===========================================================================

-- Page comments: supervisors (and the book's owner) leave notes on
-- specific pages; the owner sees them in the editor and resolves them.
--
-- Requires sql/01_admin_role.sql (public.is_admin()).
-- Run once in Supabase > SQL Editor. Safe to re-run.

-- books.id's type isn't pinned down in this repo (the editor writes its
-- own "book-…" ids, onboarding lets the database pick one), so the
-- foreign key column copies whatever type books.id actually has.
do $$
declare
  id_type text;
begin
  select format_type(a.atttypid, a.atttypmod) into id_type
  from pg_attribute a
  where a.attrelid = 'public.books'::regclass and a.attname = 'id';

  execute format($f$
    create table if not exists public.page_comments (
      id uuid primary key default gen_random_uuid(),
      book_id %s not null references public.books (id) on delete cascade,
      page_id text not null,
      author_id uuid not null references auth.users (id) on delete cascade,
      author_email text not null,
      body text not null check (char_length(body) between 1 and 2000),
      resolved boolean not null default false,
      created_at timestamptz not null default now()
    )
  $f$, id_type);
end
$$;

create index if not exists page_comments_book_idx on public.page_comments (book_id, created_at);

alter table public.page_comments enable row level security;

-- Author fields always come from the session, never from the client.
create or replace function public.page_comments_set_author()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.author_id := auth.uid();
  new.author_email := coalesce((select u.email from auth.users u where u.id = auth.uid()), 'unknown');
  new.resolved := false;
  new.created_at := now();
  return new;
end;
$$;

drop trigger if exists page_comments_set_author on public.page_comments;
create trigger page_comments_set_author
  before insert on public.page_comments
  for each row execute function public.page_comments_set_author();

-- Who may see / write comments on a book: its owner and supervisors.
create or replace function public.can_review_book(target_book text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_admin()
      or exists (select 1 from public.books b where b.id::text = target_book and b.user_id = auth.uid());
$$;
revoke all on function public.can_review_book(text) from public, anon;
grant execute on function public.can_review_book(text) to authenticated;

drop policy if exists "Owner and supervisors read comments" on public.page_comments;
create policy "Owner and supervisors read comments" on public.page_comments
  for select to authenticated
  using ((select public.can_review_book(book_id::text)));

drop policy if exists "Owner and supervisors add comments" on public.page_comments;
create policy "Owner and supervisors add comments" on public.page_comments
  for insert to authenticated
  with check ((select public.can_review_book(book_id::text)));

-- Resolving: only the `resolved` column is updatable (column grant below).
drop policy if exists "Owner and supervisors resolve comments" on public.page_comments;
create policy "Owner and supervisors resolve comments" on public.page_comments
  for update to authenticated
  using ((select public.can_review_book(book_id::text)))
  with check ((select public.can_review_book(book_id::text)));

drop policy if exists "Authors and supervisors delete comments" on public.page_comments;
create policy "Authors and supervisors delete comments" on public.page_comments
  for delete to authenticated
  using (author_id = auth.uid() or (select public.is_admin()));

revoke all on public.page_comments from anon;
revoke update on public.page_comments from authenticated;
grant select, insert, delete on public.page_comments to authenticated;
grant update (resolved) on public.page_comments to authenticated;

-- ===========================================================================
-- 03_book_print_settings.sql
-- ===========================================================================

-- Book-level print settings for KDP:
--   bleed — interior pages print to the edge (canvas extends 0.125in past the trim)
--   paper — sets the spine width on the cover (white / cream / color)
--   cover — the full wrap-around cover design (back + spine + front), as jsonb
--
-- The app keeps working before this runs (it retries saves without these
-- columns), but bleed/paper/cover won't persist until it does.
-- Run once in Supabase > SQL Editor. Safe to re-run.

alter table public.books add column if not exists bleed boolean not null default false;
alter table public.books add column if not exists paper text not null default 'white';
alter table public.books add column if not exists cover jsonb;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'books_paper_check') then
    alter table public.books add constraint books_paper_check check (paper in ('white', 'cream', 'color'));
  end if;
end
$$;

-- ===========================================================================
-- 04_book_shares.sql
-- ===========================================================================

-- Share links: a teacher shares a book, children open /share/<token> and
-- color it in the browser with no account. Children's coloring is kept on
-- their own device only — nothing they do is written back to the book.
--
-- Security model: the token is an unguessable uuid; anon can't read any
-- table directly. The only anon entry point is get_shared_book(token),
-- which returns just what coloring needs (title, trim, bleed, pages) for
-- a live, unrevoked share.
--
-- Run once in Supabase > SQL Editor. Safe to re-run.

do $$
declare
  id_type text;
begin
  select format_type(a.atttypid, a.atttypmod) into id_type
  from pg_attribute a
  where a.attrelid = 'public.books'::regclass and a.attname = 'id';

  execute format($f$
    create table if not exists public.book_shares (
      token uuid primary key default gen_random_uuid(),
      book_id %s not null references public.books (id) on delete cascade,
      created_by uuid not null default auth.uid() references auth.users (id) on delete cascade,
      created_at timestamptz not null default now(),
      revoked_at timestamptz
    )
  $f$, id_type);
end
$$;

create index if not exists book_shares_book_idx on public.book_shares (book_id);
alter table public.book_shares enable row level security;

-- Only the book's owner manages its links.
drop policy if exists "Owners read their shares" on public.book_shares;
create policy "Owners read their shares" on public.book_shares
  for select to authenticated
  using (exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

drop policy if exists "Owners create shares" on public.book_shares;
create policy "Owners create shares" on public.book_shares
  for insert to authenticated
  with check (created_by = auth.uid() and exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

drop policy if exists "Owners revoke shares" on public.book_shares;
create policy "Owners revoke shares" on public.book_shares
  for update to authenticated
  using (exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()))
  with check (exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

revoke all on public.book_shares from anon;
revoke update on public.book_shares from authenticated;
grant select, insert on public.book_shares to authenticated;
grant update (revoked_at) on public.book_shares to authenticated;

create or replace function public.get_shared_book(share_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'title', b.title,
    'trim_size', b.trim_size,
    'bleed', coalesce(to_jsonb(b) -> 'bleed', 'false'::jsonb),
    -- Clean pages for the children: no owner's coloring, no thumbnails, no blank backs.
    'pages', coalesce((
      select jsonb_agg(p - 'fillDataUrl' - 'completedAt' - 'thumbnailDataUrl' order by ord)
      from jsonb_array_elements(b.pages) with ordinality as e(p, ord)
      where not coalesce((p ->> 'isBlankBack')::boolean, false)
    ), '[]'::jsonb)
  )
  from public.book_shares s
  join public.books b on b.id = s.book_id
  where s.token = share_token and s.revoked_at is null;
$$;
revoke all on function public.get_shared_book(uuid) from public;
grant execute on function public.get_shared_book(uuid) to anon, authenticated;

-- ===========================================================================
-- 05_usage_and_templates.sql
-- ===========================================================================

-- Usage limits (AI credits per month), usage events for admin statistics,
-- and community book templates.
--
-- Requires sql/01_admin_role.sql (public.is_admin()).
-- Run once in Supabase > SQL Editor. Safe to re-run.

-- ---------------------------------------------------------------------------
-- Usage events: one row per AI image or export. AI rows count against the
-- monthly limit unless refunded (a failed generation gives its credit back).
-- ---------------------------------------------------------------------------

create table if not exists public.usage_events (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null check (kind in ('ai_image', 'ai_photo', 'export_pdf', 'export_cover')),
  units int not null default 1 check (units > 0),
  refunded boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists usage_events_user_month_idx on public.usage_events (user_id, created_at);
alter table public.usage_events enable row level security;
-- No direct client access: everything goes through the functions below.
revoke all on public.usage_events from anon, authenticated;

-- Per-user monthly AI limit; users without a row get the default.
create table if not exists public.user_quotas (
  user_id uuid primary key references auth.users (id) on delete cascade,
  ai_monthly_limit int not null check (ai_monthly_limit >= 0),
  updated_at timestamptz not null default now()
);
alter table public.user_quotas enable row level security;
revoke all on public.user_quotas from anon, authenticated;

create or replace function public.default_ai_limit() returns int language sql immutable as $$ select 20 $$;

create or replace function public.ai_used_this_month(target uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(units), 0)::int
  from public.usage_events
  where user_id = target
    and kind in ('ai_image', 'ai_photo')
    and not refunded
    and created_at >= date_trunc('month', now());
$$;
revoke all on function public.ai_used_this_month(uuid) from public, anon, authenticated;

create or replace function public.ai_limit_for(target uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select q.ai_monthly_limit from public.user_quotas q where q.user_id = target), public.default_ai_limit());
$$;
revoke all on function public.ai_limit_for(uuid) from public, anon, authenticated;

-- What the signed-in user has used / may use this month (supervisors: unlimited = null limit).
create or replace function public.my_ai_usage()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'used', public.ai_used_this_month(auth.uid()),
    'limit', case when public.is_admin() then null else public.ai_limit_for(auth.uid()) end
  );
$$;
revoke all on function public.my_ai_usage() from public, anon;
grant execute on function public.my_ai_usage() to authenticated;

-- Called by the AI API routes BEFORE contacting a provider. Atomically
-- checks the limit and records the use; returns the event id so a failure
-- can be refunded. Serialized per user so parallel requests can't overshoot.
create or replace function public.consume_ai_credit(credit_kind text, credit_units int default 1)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
  used int;
  cap int;
  event_id bigint;
begin
  if me is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  if credit_kind not in ('ai_image', 'ai_photo') or credit_units < 1 or credit_units > 10 then
    raise exception 'bad credit request' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(me::text, 0));
  used := public.ai_used_this_month(me);
  cap := case when public.is_admin() then null else public.ai_limit_for(me) end;
  if cap is not null and used + credit_units > cap then
    return jsonb_build_object('allowed', false, 'used', used, 'limit', cap);
  end if;
  insert into public.usage_events (user_id, kind, units) values (me, credit_kind, credit_units) returning id into event_id;
  return jsonb_build_object('allowed', true, 'used', used + credit_units, 'limit', cap, 'event_id', event_id);
end;
$$;
revoke all on function public.consume_ai_credit(text, int) from public, anon;
grant execute on function public.consume_ai_credit(text, int) to authenticated;

-- Give back some (or all) units of a consumed credit — only your own event.
create or replace function public.refund_ai_credit(credit_event bigint, refund_units int default null)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  ev public.usage_events%rowtype;
begin
  select * into ev from public.usage_events where id = credit_event and user_id = auth.uid() and not refunded for update;
  if not found then
    return;
  end if;
  if refund_units is null or refund_units >= ev.units then
    update public.usage_events set refunded = true where id = ev.id;
  elsif refund_units > 0 then
    update public.usage_events set units = ev.units - refund_units where id = ev.id;
  end if;
end;
$$;
revoke all on function public.refund_ai_credit(bigint, int) from public, anon;
grant execute on function public.refund_ai_credit(bigint, int) to authenticated;

-- Exports are logged for statistics only (no limit).
create or replace function public.log_export(export_kind text)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or export_kind not in ('export_pdf', 'export_cover') then
    return;
  end if;
  insert into public.usage_events (user_id, kind) values (auth.uid(), export_kind);
end;
$$;
revoke all on function public.log_export(text) from public, anon;
grant execute on function public.log_export(text) to authenticated;

create or replace function public.admin_set_ai_limit(target_user uuid, new_limit int)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if new_limit is null or new_limit < 0 or new_limit > 100000 then
    raise exception 'limit must be between 0 and 100000' using errcode = '22023';
  end if;
  insert into public.user_quotas (user_id, ai_monthly_limit) values (target_user, new_limit)
  on conflict (user_id) do update set ai_monthly_limit = excluded.ai_monthly_limit, updated_at = now();
end;
$$;
revoke all on function public.admin_set_ai_limit(uuid, int) from public, anon;
grant execute on function public.admin_set_ai_limit(uuid, int) to authenticated;

-- admin_list_users gains this month's AI use and each user's limit. The
-- return type changes, so drop and recreate.
drop function if exists public.admin_list_users();
create function public.admin_list_users()
returns table (
  id uuid,
  email text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  email_confirmed_at timestamptz,
  is_admin boolean,
  book_count bigint,
  ai_used int,
  ai_limit int
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    select
      u.id,
      u.email::text,
      u.created_at,
      u.last_sign_in_at,
      u.email_confirmed_at,
      exists (select 1 from public.app_admins a where a.user_id = u.id),
      (select count(*) from public.books b where b.user_id = u.id),
      public.ai_used_this_month(u.id),
      public.ai_limit_for(u.id)
    from auth.users u
    order by u.created_at desc;
end;
$$;
revoke all on function public.admin_list_users() from public, anon;
grant execute on function public.admin_list_users() to authenticated;

-- Aggregates for the admin dashboard.
create or replace function public.admin_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  select jsonb_build_object(
    'users', (select count(*) from auth.users),
    'active_30d', (select count(*) from auth.users where last_sign_in_at >= now() - interval '30 days'),
    'books', (select count(*) from public.books),
    'published', (select count(*) from public.books where status = 'published'),
    'pages', (select coalesce(sum(jsonb_array_length(pages)), 0) from public.books),
    'ai_month', (select coalesce(sum(units), 0) from public.usage_events where kind in ('ai_image', 'ai_photo') and not refunded and created_at >= date_trunc('month', now())),
    'exports_month', (select count(*) from public.usage_events where kind in ('export_pdf', 'export_cover') and created_at >= date_trunc('month', now())),
    'daily', (
      select coalesce(jsonb_agg(jsonb_build_object('day', d::date, 'ai', coalesce(a.ai, 0), 'exports', coalesce(a.exports, 0)) order by d), '[]'::jsonb)
      from generate_series(date_trunc('day', now()) - interval '29 days', date_trunc('day', now()), interval '1 day') d
      left join (
        select date_trunc('day', created_at) as day,
               sum(units) filter (where kind in ('ai_image', 'ai_photo') and not refunded) as ai,
               count(*) filter (where kind in ('export_pdf', 'export_cover')) as exports
        from public.usage_events
        where created_at >= date_trunc('day', now()) - interval '29 days'
        group by 1
      ) a on a.day = d
    )
  ) into result;
  return result;
end;
$$;
revoke all on function public.admin_stats() from public, anon;
grant execute on function public.admin_stats() to authenticated;

-- ---------------------------------------------------------------------------
-- Community templates: a book's pages published for others to start from.
-- ---------------------------------------------------------------------------

create table if not exists public.book_templates (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  description text not null default '' check (char_length(description) <= 500),
  trim_size text,
  bleed boolean not null default false,
  pages jsonb not null,
  page_count int not null default 0,
  thumbnail text,
  created_at timestamptz not null default now()
);
create index if not exists book_templates_created_idx on public.book_templates (created_at desc);
alter table public.book_templates enable row level security;

drop policy if exists "Signed-in users browse templates" on public.book_templates;
create policy "Signed-in users browse templates" on public.book_templates
  for select to authenticated using (true);

drop policy if exists "Authors publish templates" on public.book_templates;
create policy "Authors publish templates" on public.book_templates
  for insert to authenticated with check (author_id = auth.uid());

-- Authors take down their own; supervisors moderate any.
drop policy if exists "Authors and supervisors remove templates" on public.book_templates;
create policy "Authors and supervisors remove templates" on public.book_templates
  for delete to authenticated using (author_id = auth.uid() or (select public.is_admin()));

revoke all on public.book_templates from anon;
revoke update on public.book_templates from authenticated;
grant select, insert, delete on public.book_templates to authenticated;
