-- GENERATED by `npm run sql:all` — do not edit; edit the numbered files instead.
-- Contains, in order: 00_books.sql, 01_admin_role.sql, 02_page_comments.sql, 03_book_print_settings.sql, 04_book_shares.sql, 05_usage_and_templates.sql, 06_user_library.sql, 07_image_storage.sql, 08_user_media.sql, 09_billing.sql, 10_kid_groups.sql, 11_book_members.sql, 12_app_errors.sql
-- Safe to re-run.

-- ===========================================================================
-- 00_books.sql
-- ===========================================================================

-- The base table: one row per book, every page in `pages` (jsonb array).
--
-- This is the schema the app was set up with; on an existing project it
-- changes nothing (same table, same policy names). On a NEW Supabase
-- project it must run first — everything in 01–05 builds on public.books.
-- Run once in Supabase > SQL Editor. Safe to re-run.

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  pages jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published')),
  collection text,
  trim_size text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_user_id_idx on public.books (user_id);

alter table public.books enable row level security;

-- Each user sees and changes only their own books. (Supervisors get extra
-- read/delete access in 01_admin_role.sql.) The update policy has no
-- separate WITH CHECK, so Postgres applies the USING condition to the new
-- row too: nobody can hand a book to another user_id.
drop policy if exists "select own books" on public.books;
create policy "select own books" on public.books for select using (auth.uid() = user_id);

drop policy if exists "insert own books" on public.books;
create policy "insert own books" on public.books for insert with check (auth.uid() = user_id);

drop policy if exists "update own books" on public.books;
create policy "update own books" on public.books for update using (auth.uid() = user_id);

drop policy if exists "delete own books" on public.books;
create policy "delete own books" on public.books for delete using (auth.uid() = user_id);

-- ===========================================================================
-- 01_admin_role.sql
-- ===========================================================================

-- Supervisor / admin role.
--
-- Admins can READ and DELETE every user's books and list all accounts
-- (the /studio/admin page). They deliberately can't UPDATE other users'
-- books: saveBook() upserts with the *current* user's id, so an admin
-- editing someone else's book would silently take ownership of it.
--
-- Run once in Supabase > SQL Editor. Safe to re-run.

-- Who is an admin. RLS on with no policies: the table is invisible to the
-- client; only the SECURITY DEFINER functions below read it.
create table if not exists public.app_admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.app_admins enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.app_admins where user_id = auth.uid());
$$;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- Additive to the existing "own rows only" policies on books.
drop policy if exists "Admins can read all books" on public.books;
create policy "Admins can read all books" on public.books
  for select to authenticated
  using ((select public.is_admin()));

drop policy if exists "Admins can delete any book" on public.books;
create policy "Admins can delete any book" on public.books
  for delete to authenticated
  using ((select public.is_admin()));

-- auth.users isn't exposed through the API, so the user list goes through
-- this function, which refuses anyone who isn't an admin.
-- (sql/05_usage_and_templates.sql redefines it with AI-usage
-- columns — run that one again after re-running this file.)
drop function if exists public.admin_list_users();
create function public.admin_list_users()
returns table (
  id uuid,
  email text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  email_confirmed_at timestamptz,
  is_admin boolean,
  book_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  return query
    select
      u.id,
      u.email::text,
      u.created_at,
      u.last_sign_in_at,
      u.email_confirmed_at,
      exists (select 1 from public.app_admins a where a.user_id = u.id),
      (select count(*) from public.books b where b.user_id = u.id)
    from auth.users u
    order by u.created_at desc;
end;
$$;
revoke all on function public.admin_list_users() from public, anon;
grant execute on function public.admin_list_users() to authenticated;

-- Promote/demote another account from the admin page. A supervisor can't
-- demote themselves, so the app can never end up with nobody able to
-- manage it.
create or replace function public.admin_set_supervisor(target_user uuid, make_supervisor boolean)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if target_user = auth.uid() and not make_supervisor then
    raise exception 'You can''t remove your own supervisor access.' using errcode = '42501';
  end if;

  if make_supervisor then
    insert into public.app_admins (user_id) values (target_user) on conflict do nothing;
  else
    delete from public.app_admins where user_id = target_user;
  end if;
end;
$$;
revoke all on function public.admin_set_supervisor(uuid, boolean) from public, anon;
grant execute on function public.admin_set_supervisor(uuid, boolean) to authenticated;

-- Make the FIRST supervisor (create the account under Authentication > Users);
-- after that, supervisors can promote others from /studio/admin:
--   insert into public.app_admins (user_id)
--   select id from auth.users where email = 'supervisor@example.com'
--   on conflict do nothing;

-- ===========================================================================
-- 02_page_comments.sql
-- ===========================================================================

-- Page comments: supervisors (and the book's owner) leave notes on
-- specific pages; the owner sees them in the editor and resolves them.
--
-- Requires sql/01_admin_role.sql (public.is_admin()).
-- Run once in Supabase > SQL Editor. Safe to re-run.

-- books.id's type isn't pinned down in this repo (the editor writes its
-- own "book-…" ids, onboarding lets the database pick one), so the
-- foreign key column copies whatever type books.id actually has.
do $$
declare
  id_type text;
begin
  select format_type(a.atttypid, a.atttypmod) into id_type
  from pg_attribute a
  where a.attrelid = 'public.books'::regclass and a.attname = 'id';

  execute format($f$
    create table if not exists public.page_comments (
      id uuid primary key default gen_random_uuid(),
      book_id %s not null references public.books (id) on delete cascade,
      page_id text not null,
      author_id uuid not null references auth.users (id) on delete cascade,
      author_email text not null,
      body text not null check (char_length(body) between 1 and 2000),
      resolved boolean not null default false,
      created_at timestamptz not null default now()
    )
  $f$, id_type);
end
$$;

create index if not exists page_comments_book_idx on public.page_comments (book_id, created_at);

alter table public.page_comments enable row level security;

-- Author fields always come from the session, never from the client.
create or replace function public.page_comments_set_author()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.author_id := auth.uid();
  new.author_email := coalesce((select u.email from auth.users u where u.id = auth.uid()), 'unknown');
  new.resolved := false;
  new.created_at := now();
  return new;
end;
$$;

drop trigger if exists page_comments_set_author on public.page_comments;
create trigger page_comments_set_author
  before insert on public.page_comments
  for each row execute function public.page_comments_set_author();

-- Who may see / write comments on a book: its owner and supervisors.
create or replace function public.can_review_book(target_book text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_admin()
      or exists (select 1 from public.books b where b.id::text = target_book and b.user_id = auth.uid());
$$;
revoke all on function public.can_review_book(text) from public, anon;
grant execute on function public.can_review_book(text) to authenticated;

drop policy if exists "Owner and supervisors read comments" on public.page_comments;
create policy "Owner and supervisors read comments" on public.page_comments
  for select to authenticated
  using ((select public.can_review_book(book_id::text)));

drop policy if exists "Owner and supervisors add comments" on public.page_comments;
create policy "Owner and supervisors add comments" on public.page_comments
  for insert to authenticated
  with check ((select public.can_review_book(book_id::text)));

-- Resolving: only the `resolved` column is updatable (column grant below).
drop policy if exists "Owner and supervisors resolve comments" on public.page_comments;
create policy "Owner and supervisors resolve comments" on public.page_comments
  for update to authenticated
  using ((select public.can_review_book(book_id::text)))
  with check ((select public.can_review_book(book_id::text)));

drop policy if exists "Authors and supervisors delete comments" on public.page_comments;
create policy "Authors and supervisors delete comments" on public.page_comments
  for delete to authenticated
  using (author_id = auth.uid() or (select public.is_admin()));

revoke all on public.page_comments from anon;
revoke update on public.page_comments from authenticated;
grant select, insert, delete on public.page_comments to authenticated;
grant update (resolved) on public.page_comments to authenticated;

-- ===========================================================================
-- 03_book_print_settings.sql
-- ===========================================================================

-- Book-level print settings for KDP:
--   bleed — interior pages print to the edge (canvas extends 0.125in past the trim)
--   paper — sets the spine width on the cover (white / cream / color)
--   cover — the full wrap-around cover design (back + spine + front), as jsonb
--
-- The app keeps working before this runs (it retries saves without these
-- columns), but bleed/paper/cover won't persist until it does.
-- Run once in Supabase > SQL Editor. Safe to re-run.

alter table public.books add column if not exists bleed boolean not null default false;
alter table public.books add column if not exists paper text not null default 'white';
alter table public.books add column if not exists cover jsonb;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'books_paper_check') then
    alter table public.books add constraint books_paper_check check (paper in ('white', 'cream', 'color'));
  end if;
end
$$;

-- ===========================================================================
-- 04_book_shares.sql
-- ===========================================================================

-- Share links: a teacher shares a book, children open /share/<token> and
-- color it in the browser with no account. Children's coloring is kept on
-- their own device only — nothing they do is written back to the book.
--
-- Security model: the token is an unguessable uuid; anon can't read any
-- table directly. The only anon entry point is get_shared_book(token),
-- which returns just what coloring needs (title, trim, bleed, pages) for
-- a live, unrevoked share.
--
-- Run once in Supabase > SQL Editor. Safe to re-run.

do $$
declare
  id_type text;
begin
  select format_type(a.atttypid, a.atttypmod) into id_type
  from pg_attribute a
  where a.attrelid = 'public.books'::regclass and a.attname = 'id';

  execute format($f$
    create table if not exists public.book_shares (
      token uuid primary key default gen_random_uuid(),
      book_id %s not null references public.books (id) on delete cascade,
      created_by uuid not null default auth.uid() references auth.users (id) on delete cascade,
      created_at timestamptz not null default now(),
      revoked_at timestamptz
    )
  $f$, id_type);
end
$$;

create index if not exists book_shares_book_idx on public.book_shares (book_id);
alter table public.book_shares enable row level security;

-- Only the book's owner manages its links.
drop policy if exists "Owners read their shares" on public.book_shares;
create policy "Owners read their shares" on public.book_shares
  for select to authenticated
  using (exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

drop policy if exists "Owners create shares" on public.book_shares;
create policy "Owners create shares" on public.book_shares
  for insert to authenticated
  with check (created_by = auth.uid() and exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

drop policy if exists "Owners revoke shares" on public.book_shares;
create policy "Owners revoke shares" on public.book_shares
  for update to authenticated
  using (exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()))
  with check (exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

revoke all on public.book_shares from anon;
revoke update on public.book_shares from authenticated;
grant select, insert on public.book_shares to authenticated;
grant update (revoked_at) on public.book_shares to authenticated;

create or replace function public.get_shared_book(share_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'title', b.title,
    'trim_size', b.trim_size,
    'bleed', coalesce(to_jsonb(b) -> 'bleed', 'false'::jsonb),
    -- Clean pages for the children: no owner's coloring, no thumbnails, no blank backs.
    'pages', coalesce((
      select jsonb_agg(p - 'fillDataUrl' - 'completedAt' - 'thumbnailDataUrl' order by ord)
      from jsonb_array_elements(b.pages) with ordinality as e(p, ord)
      where not coalesce((p ->> 'isBlankBack')::boolean, false)
    ), '[]'::jsonb)
  )
  from public.book_shares s
  join public.books b on b.id = s.book_id
  where s.token = share_token and s.revoked_at is null;
$$;
revoke all on function public.get_shared_book(uuid) from public;
grant execute on function public.get_shared_book(uuid) to anon, authenticated;

-- ===========================================================================
-- 05_usage_and_templates.sql
-- ===========================================================================

-- Usage limits (AI credits per month), usage events for admin statistics,
-- and community book templates.
--
-- Requires sql/01_admin_role.sql (public.is_admin()).
-- Run once in Supabase > SQL Editor. Safe to re-run.

-- ---------------------------------------------------------------------------
-- Usage events: one row per AI image or export. AI rows count against the
-- monthly limit unless refunded (a failed generation gives its credit back).
-- ---------------------------------------------------------------------------

create table if not exists public.usage_events (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null check (kind in ('ai_image', 'ai_photo', 'export_pdf', 'export_cover')),
  units int not null default 1 check (units > 0),
  refunded boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists usage_events_user_month_idx on public.usage_events (user_id, created_at);
alter table public.usage_events enable row level security;
-- No direct client access: everything goes through the functions below.
revoke all on public.usage_events from anon, authenticated;

-- Per-user monthly AI limit; users without a row get the default.
create table if not exists public.user_quotas (
  user_id uuid primary key references auth.users (id) on delete cascade,
  ai_monthly_limit int not null check (ai_monthly_limit >= 0),
  updated_at timestamptz not null default now()
);
alter table public.user_quotas enable row level security;
revoke all on public.user_quotas from anon, authenticated;

create or replace function public.default_ai_limit() returns int language sql immutable as $$ select 20 $$;

create or replace function public.ai_used_this_month(target uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(units), 0)::int
  from public.usage_events
  where user_id = target
    and kind in ('ai_image', 'ai_photo')
    and not refunded
    and created_at >= date_trunc('month', now());
$$;
revoke all on function public.ai_used_this_month(uuid) from public, anon, authenticated;

create or replace function public.ai_limit_for(target uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select q.ai_monthly_limit from public.user_quotas q where q.user_id = target), public.default_ai_limit());
$$;
revoke all on function public.ai_limit_for(uuid) from public, anon, authenticated;

-- What the signed-in user has used / may use this month (supervisors: unlimited = null limit).
create or replace function public.my_ai_usage()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'used', public.ai_used_this_month(auth.uid()),
    'limit', case when public.is_admin() then null else public.ai_limit_for(auth.uid()) end
  );
$$;
revoke all on function public.my_ai_usage() from public, anon;
grant execute on function public.my_ai_usage() to authenticated;

-- Called by the AI API routes BEFORE contacting a provider. Atomically
-- checks the limit and records the use; returns the event id so a failure
-- can be refunded. Serialized per user so parallel requests can't overshoot.
create or replace function public.consume_ai_credit(credit_kind text, credit_units int default 1)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
  used int;
  cap int;
  event_id bigint;
begin
  if me is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  if credit_kind not in ('ai_image', 'ai_photo') or credit_units < 1 or credit_units > 10 then
    raise exception 'bad credit request' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(me::text, 0));
  used := public.ai_used_this_month(me);
  cap := case when public.is_admin() then null else public.ai_limit_for(me) end;
  if cap is not null and used + credit_units > cap then
    return jsonb_build_object('allowed', false, 'used', used, 'limit', cap);
  end if;
  insert into public.usage_events (user_id, kind, units) values (me, credit_kind, credit_units) returning id into event_id;
  return jsonb_build_object('allowed', true, 'used', used + credit_units, 'limit', cap, 'event_id', event_id);
end;
$$;
revoke all on function public.consume_ai_credit(text, int) from public, anon;
grant execute on function public.consume_ai_credit(text, int) to authenticated;

-- Give back some (or all) units of a consumed credit — only your own event.
create or replace function public.refund_ai_credit(credit_event bigint, refund_units int default null)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  ev public.usage_events%rowtype;
begin
  select * into ev from public.usage_events where id = credit_event and user_id = auth.uid() and not refunded for update;
  if not found then
    return;
  end if;
  if refund_units is null or refund_units >= ev.units then
    update public.usage_events set refunded = true where id = ev.id;
  elsif refund_units > 0 then
    update public.usage_events set units = ev.units - refund_units where id = ev.id;
  end if;
end;
$$;
revoke all on function public.refund_ai_credit(bigint, int) from public, anon;
grant execute on function public.refund_ai_credit(bigint, int) to authenticated;

-- Exports are logged for statistics only (no limit).
create or replace function public.log_export(export_kind text)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or export_kind not in ('export_pdf', 'export_cover') then
    return;
  end if;
  insert into public.usage_events (user_id, kind) values (auth.uid(), export_kind);
end;
$$;
revoke all on function public.log_export(text) from public, anon;
grant execute on function public.log_export(text) to authenticated;

create or replace function public.admin_set_ai_limit(target_user uuid, new_limit int)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if new_limit is null or new_limit < 0 or new_limit > 100000 then
    raise exception 'limit must be between 0 and 100000' using errcode = '22023';
  end if;
  insert into public.user_quotas (user_id, ai_monthly_limit) values (target_user, new_limit)
  on conflict (user_id) do update set ai_monthly_limit = excluded.ai_monthly_limit, updated_at = now();
end;
$$;
revoke all on function public.admin_set_ai_limit(uuid, int) from public, anon;
grant execute on function public.admin_set_ai_limit(uuid, int) to authenticated;

-- admin_list_users gains this month's AI use and each user's limit. The
-- return type changes, so drop and recreate.
drop function if exists public.admin_list_users();
create function public.admin_list_users()
returns table (
  id uuid,
  email text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  email_confirmed_at timestamptz,
  is_admin boolean,
  book_count bigint,
  ai_used int,
  ai_limit int
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    select
      u.id,
      u.email::text,
      u.created_at,
      u.last_sign_in_at,
      u.email_confirmed_at,
      exists (select 1 from public.app_admins a where a.user_id = u.id),
      (select count(*) from public.books b where b.user_id = u.id),
      public.ai_used_this_month(u.id),
      public.ai_limit_for(u.id)
    from auth.users u
    order by u.created_at desc;
end;
$$;
revoke all on function public.admin_list_users() from public, anon;
grant execute on function public.admin_list_users() to authenticated;

-- Aggregates for the admin dashboard.
create or replace function public.admin_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  select jsonb_build_object(
    'users', (select count(*) from auth.users),
    'active_30d', (select count(*) from auth.users where last_sign_in_at >= now() - interval '30 days'),
    'books', (select count(*) from public.books),
    'published', (select count(*) from public.books where status = 'published'),
    'pages', (select coalesce(sum(jsonb_array_length(pages)), 0) from public.books),
    'ai_month', (select coalesce(sum(units), 0) from public.usage_events where kind in ('ai_image', 'ai_photo') and not refunded and created_at >= date_trunc('month', now())),
    'exports_month', (select count(*) from public.usage_events where kind in ('export_pdf', 'export_cover') and created_at >= date_trunc('month', now())),
    'daily', (
      select coalesce(jsonb_agg(jsonb_build_object('day', d::date, 'ai', coalesce(a.ai, 0), 'exports', coalesce(a.exports, 0)) order by d), '[]'::jsonb)
      from generate_series(date_trunc('day', now()) - interval '29 days', date_trunc('day', now()), interval '1 day') d
      left join (
        select date_trunc('day', created_at) as day,
               sum(units) filter (where kind in ('ai_image', 'ai_photo') and not refunded) as ai,
               count(*) filter (where kind in ('export_pdf', 'export_cover')) as exports
        from public.usage_events
        where created_at >= date_trunc('day', now()) - interval '29 days'
        group by 1
      ) a on a.day = d
    )
  ) into result;
  return result;
end;
$$;
revoke all on function public.admin_stats() from public, anon;
grant execute on function public.admin_stats() to authenticated;

-- ---------------------------------------------------------------------------
-- Community templates: a book's pages published for others to start from.
-- ---------------------------------------------------------------------------

create table if not exists public.book_templates (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  description text not null default '' check (char_length(description) <= 500),
  trim_size text,
  bleed boolean not null default false,
  pages jsonb not null,
  page_count int not null default 0,
  thumbnail text,
  created_at timestamptz not null default now()
);
create index if not exists book_templates_created_idx on public.book_templates (created_at desc);
alter table public.book_templates enable row level security;

drop policy if exists "Signed-in users browse templates" on public.book_templates;
create policy "Signed-in users browse templates" on public.book_templates
  for select to authenticated using (true);

drop policy if exists "Authors publish templates" on public.book_templates;
create policy "Authors publish templates" on public.book_templates
  for insert to authenticated with check (author_id = auth.uid());

-- Authors take down their own; supervisors moderate any.
drop policy if exists "Authors and supervisors remove templates" on public.book_templates;
create policy "Authors and supervisors remove templates" on public.book_templates
  for delete to authenticated using (author_id = auth.uid() or (select public.is_admin()));

revoke all on public.book_templates from anon;
revoke update on public.book_templates from authenticated;
grant select, insert, delete on public.book_templates to authenticated;

-- ===========================================================================
-- 06_user_library.sql
-- ===========================================================================

-- A user's own library, kept with the account instead of on one device:
-- "My stamps" (saved pieces to reuse in any book) and book version history.
--
-- Requires sql/00_books.sql. Run once in Supabase > SQL Editor. Safe to re-run.
-- Until it runs, the app keeps both on the device only (as before).

-- ---------------------------------------------------------------------------
-- My stamps
-- ---------------------------------------------------------------------------

create table if not exists public.user_stamps (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  id text not null check (char_length(id) between 1 and 80),
  name text not null default '' check (char_length(name) <= 120),
  preview text not null,
  objects jsonb not null,
  width real not null,
  height real not null,
  created_at timestamptz not null default now(),
  primary key (user_id, id)
);
alter table public.user_stamps enable row level security;

drop policy if exists "Users manage their own stamps" on public.user_stamps;
create policy "Users manage their own stamps" on public.user_stamps
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

revoke all on public.user_stamps from anon;
grant select, insert, update, delete on public.user_stamps to authenticated;

-- ---------------------------------------------------------------------------
-- Book versions: snapshots of a book's pages to go back to.
-- ---------------------------------------------------------------------------

create table if not exists public.book_versions (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  id text not null check (char_length(id) between 1 and 80),
  book_id uuid not null references public.books (id) on delete cascade,
  at timestamptz not null default now(),
  title text not null default '',
  page_count int not null default 0,
  signature text not null default '',
  manual boolean not null default false,
  pages jsonb not null,
  primary key (user_id, id)
);
create index if not exists book_versions_book_idx on public.book_versions (book_id, at desc);
alter table public.book_versions enable row level security;

-- Only for books the user owns: a version can't be attached to someone else's book.
drop policy if exists "Users manage versions of their own books" on public.book_versions;
create policy "Users manage versions of their own books" on public.book_versions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

revoke all on public.book_versions from anon;
grant select, insert, update, delete on public.book_versions to authenticated;

-- ===========================================================================
-- 07_image_storage.sql
-- ===========================================================================

-- Pictures out of the book rows: a public Storage bucket the editor uploads
-- a book's pictures to, so a book's saved data holds short links instead of
-- megabytes of embedded images (faster saves, smaller rows).
--
-- Run once in Supabase > SQL Editor. Safe to re-run.
-- Until it runs, pictures stay embedded in the book (as before).
--
-- The bucket is public-read on purpose: pages are drawn on a canvas, which
-- needs to read the picture without credentials (and share links for
-- children are anonymous). File names are a hash of the picture inside the
-- owner's own folder, so they can't be guessed or listed by others.

do $$
begin
  -- Supabase only: plain Postgres (the test database) has no storage schema.
  if to_regclass('storage.buckets') is null then
    raise notice 'storage schema not found — skipping the image bucket';
    return;
  end if;

  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('book-images', 'book-images', true, 10485760, array['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'])
  on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

  -- Upload and delete only inside a folder named after your own user id.
  execute 'drop policy if exists "Users upload their own book images" on storage.objects';
  execute $p$create policy "Users upload their own book images" on storage.objects
    for insert to authenticated
    with check (bucket_id = 'book-images' and (storage.foldername(name))[1] = auth.uid()::text)$p$;

  execute 'drop policy if exists "Users delete their own book images" on storage.objects';
  execute $p$create policy "Users delete their own book images" on storage.objects
    for delete to authenticated
    using (bucket_id = 'book-images' and (storage.foldername(name))[1] = auth.uid()::text)$p$;
end $$;

-- ===========================================================================
-- 08_user_media.sql
-- ===========================================================================

-- Media library: every picture a user has uploaded or generated, to use
-- again in any book. The files themselves live in the book-images bucket
-- (sql/07_image_storage.sql); this table is the catalogue — name, size,
-- where it came from.
--
-- Requires sql/07_image_storage.sql. Run once in Supabase > SQL Editor. Safe to re-run.

create table if not exists public.user_media (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- The file's path inside the bucket ("<user id>/<hash>.png") and its public link.
  path text not null check (char_length(path) between 3 and 300),
  url text not null check (char_length(url) <= 600),
  name text not null default '' check (char_length(name) <= 160),
  mime text not null default '',
  width int not null default 0,
  height int not null default 0,
  source text not null default 'upload' check (source in ('upload', 'ai')),
  created_at timestamptz not null default now(),
  -- The same picture added twice is one entry.
  unique (user_id, path)
);
create index if not exists user_media_user_idx on public.user_media (user_id, created_at desc);
alter table public.user_media enable row level security;

-- A user can only catalogue files in their own folder.
drop policy if exists "Users manage their own media" on public.user_media;
create policy "Users manage their own media" on public.user_media
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and path like auth.uid()::text || '/%');

revoke all on public.user_media from anon;
grant select, insert, update, delete on public.user_media to authenticated;

-- ===========================================================================
-- 09_billing.sql
-- ===========================================================================

-- Plans (Free / Pro / Studio) and AI credit packs, paid through Stripe.
--
-- Requires sql/05_usage_and_templates.sql (usage_events, consume_ai_credit).
-- Safe to re-run.
--
-- How the AI limit works after this file:
--   * every plan has a monthly allowance (Free 20, Pro 300, Studio 1500);
--     a supervisor-set limit (user_quotas) still wins over the plan;
--   * credits bought in packs never expire and are only used once the
--     month's allowance has run out (usage_events.from_extra marks those).
--
-- Rows in subscriptions / credit_purchases are written only by the Stripe
-- webhook (/api/billing/webhook) with the service-role key, never by the
-- browser: users can read their own, nothing else.

create table if not exists public.subscriptions (
  user_id uuid primary key references auth.users (id) on delete cascade,
  plan text not null default 'free' check (plan in ('free', 'pro', 'studio')),
  status text not null default 'active',
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);
alter table public.subscriptions enable row level security;
revoke all on public.subscriptions from anon, authenticated;
grant select on public.subscriptions to authenticated;
drop policy if exists "read own subscription" on public.subscriptions;
create policy "read own subscription" on public.subscriptions for select to authenticated using (user_id = auth.uid());

create table if not exists public.credit_purchases (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  credits int not null check (credits > 0),
  -- One row per Stripe Checkout session: a webhook delivered twice adds the credits once.
  stripe_session_id text not null unique,
  created_at timestamptz not null default now()
);
create index if not exists credit_purchases_user_idx on public.credit_purchases (user_id);
alter table public.credit_purchases enable row level security;
revoke all on public.credit_purchases from anon, authenticated;
grant select on public.credit_purchases to authenticated;
drop policy if exists "read own purchases" on public.credit_purchases;
create policy "read own purchases" on public.credit_purchases for select to authenticated using (user_id = auth.uid());

alter table public.usage_events add column if not exists from_extra boolean not null default false;

create or replace function public.plan_ai_limit(plan_name text) returns int language sql immutable as $$
  select case plan_name when 'pro' then 300 when 'studio' then 1500 else public.default_ai_limit() end
$$;

-- The plan that counts: a paid plan only while Stripe says it's active (or in its grace period).
create or replace function public.plan_for(target uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select s.plan from public.subscriptions s
      where s.user_id = target and s.status in ('active', 'trialing', 'past_due')),
    'free');
$$;
revoke all on function public.plan_for(uuid) from public, anon, authenticated;

create or replace function public.ai_limit_for(target uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select q.ai_monthly_limit from public.user_quotas q where q.user_id = target), public.plan_ai_limit(public.plan_for(target)));
$$;
revoke all on function public.ai_limit_for(uuid) from public, anon, authenticated;

-- This month's use of the allowance — bought credits don't count here.
create or replace function public.ai_used_this_month(target uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(units), 0)::int
  from public.usage_events
  where user_id = target
    and kind in ('ai_image', 'ai_photo')
    and not refunded
    and not from_extra
    and created_at >= date_trunc('month', now());
$$;
revoke all on function public.ai_used_this_month(uuid) from public, anon, authenticated;

-- Bought credits not yet used (they never expire).
create or replace function public.extra_credits_left(target uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select greatest(0,
    coalesce((select sum(p.credits) from public.credit_purchases p where p.user_id = target), 0)
    - coalesce((select sum(e.units) from public.usage_events e where e.user_id = target and e.from_extra and not e.refunded), 0)
  )::int;
$$;
revoke all on function public.extra_credits_left(uuid) from public, anon, authenticated;

create or replace function public.my_ai_usage()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'used', public.ai_used_this_month(auth.uid()),
    'limit', case when public.is_admin() then null else public.ai_limit_for(auth.uid()) end,
    'extra', public.extra_credits_left(auth.uid()),
    'plan', public.plan_for(auth.uid())
  );
$$;
revoke all on function public.my_ai_usage() from public, anon;
grant execute on function public.my_ai_usage() to authenticated;

-- Same contract as before (allowed/used/limit/event_id), plus 'extra'.
-- The month's allowance first; when it can't cover the request, bought credits.
create or replace function public.consume_ai_credit(credit_kind text, credit_units int default 1)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
  used int;
  cap int;
  extra int;
  event_id bigint;
begin
  if me is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  if credit_kind not in ('ai_image', 'ai_photo') or credit_units < 1 or credit_units > 10 then
    raise exception 'bad credit request' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(me::text, 0));
  used := public.ai_used_this_month(me);
  cap := case when public.is_admin() then null else public.ai_limit_for(me) end;
  extra := public.extra_credits_left(me);
  if cap is null or used + credit_units <= cap then
    insert into public.usage_events (user_id, kind, units) values (me, credit_kind, credit_units) returning id into event_id;
    return jsonb_build_object('allowed', true, 'used', used + credit_units, 'limit', cap, 'extra', extra, 'event_id', event_id);
  end if;
  if extra >= credit_units then
    insert into public.usage_events (user_id, kind, units, from_extra) values (me, credit_kind, credit_units, true) returning id into event_id;
    return jsonb_build_object('allowed', true, 'used', used, 'limit', cap, 'extra', extra - credit_units, 'event_id', event_id);
  end if;
  return jsonb_build_object('allowed', false, 'used', used, 'limit', cap, 'extra', extra);
end;
$$;
revoke all on function public.consume_ai_credit(text, int) from public, anon;
grant execute on function public.consume_ai_credit(text, int) to authenticated;

-- ===========================================================================
-- 10_kid_groups.sql
-- ===========================================================================

-- Classes and families: a grown-up (teacher or parent) makes a group of
-- children, gives it books to color, and sees every child's finished
-- pages — kept with the account, not just on a device.
--
-- Children have no accounts and no email. They join at /kids with the
-- group's code, tap their name, then their two-picture password. That
-- login hands the device a secret token (kid_members.token); every
-- child-side call below takes that token, nothing else. The grown-up can
-- reset it to sign a lost tablet out.
--
-- Anon can't read any table here directly: the only child entry points
-- are the security-definer functions at the bottom.
--
-- Requires sql/00_books.sql. Safe to re-run.

-- Join codes avoid look-alike characters (no 0/O, 1/I/L).
create or replace function public.new_group_code() returns text language sql volatile as $$
  select string_agg(substr('ABCDEFGHJKMNPQRSTUVWXYZ23456789', 1 + floor(random() * 31)::int, 1), '')
  from generate_series(1, 6);
$$;

-- Two pictures out of nine, e.g. {3,7}.
create or replace function public.new_picture_pin() returns int[] language sql volatile as $$
  select array[floor(random() * 9)::int, floor(random() * 9)::int];
$$;

create table if not exists public.kid_groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind text not null default 'class' check (kind in ('class', 'family')),
  name text not null check (char_length(name) between 1 and 80),
  code text not null unique default public.new_group_code(),
  created_at timestamptz not null default now()
);
create index if not exists kid_groups_owner_idx on public.kid_groups (owner_id);

create table if not exists public.kid_members (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.kid_groups (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 40),
  avatar int not null default 0 check (avatar between 0 and 9),
  pin int[] not null default public.new_picture_pin() check (array_length(pin, 1) = 2 and pin[1] between 0 and 8 and pin[2] between 0 and 8),
  token uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now()
);
create index if not exists kid_members_group_idx on public.kid_members (group_id);

create table if not exists public.kid_group_books (
  group_id uuid not null references public.kid_groups (id) on delete cascade,
  book_id uuid not null references public.books (id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (group_id, book_id)
);

-- One row per child per page they've colored.
create table if not exists public.kid_work (
  member_id uuid not null references public.kid_members (id) on delete cascade,
  book_id uuid not null references public.books (id) on delete cascade,
  page_id text not null check (char_length(page_id) <= 100),
  fill text check (fill is null or octet_length(fill) <= 4000000),
  thumb text check (thumb is null or octet_length(thumb) <= 400000),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  -- From the grown-up: a sticker (index into the app's sticker set) and a short note.
  sticker int check (sticker is null or sticker between 0 and 9),
  comment text check (comment is null or char_length(comment) <= 300),
  primary key (member_id, book_id, page_id)
);
create index if not exists kid_work_book_idx on public.kid_work (book_id);

alter table public.kid_groups enable row level security;
alter table public.kid_members enable row level security;
alter table public.kid_group_books enable row level security;
alter table public.kid_work enable row level security;
revoke all on public.kid_groups, public.kid_members, public.kid_group_books, public.kid_work from anon;

create or replace function public.owns_kid_group(target uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.kid_groups g where g.id = target and g.owner_id = auth.uid());
$$;
revoke all on function public.owns_kid_group(uuid) from public, anon;
grant execute on function public.owns_kid_group(uuid) to authenticated;

-- Groups: the owner does everything; the code can't be chosen, only regenerated.
grant select, insert, delete on public.kid_groups to authenticated;
grant update (name, kind, code) on public.kid_groups to authenticated;
drop policy if exists "own groups" on public.kid_groups;
create policy "own groups" on public.kid_groups for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

grant select, insert, delete on public.kid_members to authenticated;
grant update (name, avatar, pin, token) on public.kid_members to authenticated;
drop policy if exists "own group members" on public.kid_members;
create policy "own group members" on public.kid_members for all to authenticated using (public.owns_kid_group(group_id)) with check (public.owns_kid_group(group_id));

-- Only your own books go to your own groups.
grant select, insert, delete on public.kid_group_books to authenticated;
drop policy if exists "own group books" on public.kid_group_books;
create policy "own group books" on public.kid_group_books for all to authenticated
  using (public.owns_kid_group(group_id))
  with check (public.owns_kid_group(group_id) and exists (select 1 from public.books b where b.id = book_id and b.user_id = auth.uid()));

-- The grown-up reads their children's work and can only add a sticker or a note.
grant select on public.kid_work to authenticated;
grant update (sticker, comment) on public.kid_work to authenticated;
drop policy if exists "read own kids work" on public.kid_work;
create policy "read own kids work" on public.kid_work for select to authenticated
  using (exists (select 1 from public.kid_members m where m.id = member_id and public.owns_kid_group(m.group_id)));
drop policy if exists "reward own kids work" on public.kid_work;
create policy "reward own kids work" on public.kid_work for update to authenticated
  using (exists (select 1 from public.kid_members m where m.id = member_id and public.owns_kid_group(m.group_id)));

-- ---------------------------------------------------------------------------
-- Child side (anon). Nothing here returns a pin or a token except kid_login.
-- ---------------------------------------------------------------------------

-- The join screen: the group's name and the children to pick from.
create or replace function public.kid_group_lookup(group_code text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'name', g.name,
    'kind', g.kind,
    'members', coalesce((select jsonb_agg(jsonb_build_object('id', m.id, 'name', m.name, 'avatar', m.avatar) order by m.name) from public.kid_members m where m.group_id = g.id), '[]'::jsonb)
  )
  from public.kid_groups g
  where g.code = upper(trim(group_code));
$$;
revoke all on function public.kid_group_lookup(text) from public;
grant execute on function public.kid_group_lookup(text) to anon, authenticated;

-- Right pictures → the device's token. Wrong → null.
create or replace function public.kid_login(group_code text, member uuid, picture_pin int[])
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select m.token
  from public.kid_members m
  join public.kid_groups g on g.id = m.group_id
  where g.code = upper(trim(group_code)) and m.id = member and m.pin = picture_pin;
$$;
revoke all on function public.kid_login(text, uuid, int[]) from public;
grant execute on function public.kid_login(text, uuid, int[]) to anon, authenticated;

-- The child's home: their books with progress, and the stickers they've been given.
create or replace function public.kid_home(kid_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'name', m.name,
    'avatar', m.avatar,
    'group', g.name,
    'books', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', b.id,
        'title', b.title,
        'pages', (select count(*) from jsonb_array_elements(b.pages) p where not coalesce((p ->> 'isBlankBack')::boolean, false)),
        'done', (select count(*) from public.kid_work w where w.member_id = m.id and w.book_id = b.id and w.completed_at is not null),
        'cover', (select w.thumb from public.kid_work w where w.member_id = m.id and w.book_id = b.id and w.thumb is not null order by w.updated_at desc limit 1)
      ) order by gb.assigned_at desc)
      from public.kid_group_books gb join public.books b on b.id = gb.book_id
      where gb.group_id = g.id
    ), '[]'::jsonb),
    'stickers', coalesce((select jsonb_agg(w.sticker order by w.updated_at) from public.kid_work w where w.member_id = m.id and w.sticker is not null), '[]'::jsonb),
    'notes', coalesce((select jsonb_agg(jsonb_build_object('book_id', w.book_id, 'page_id', w.page_id, 'comment', w.comment) order by w.updated_at desc) from public.kid_work w where w.member_id = m.id and w.comment is not null), '[]'::jsonb)
  )
  from public.kid_members m
  join public.kid_groups g on g.id = m.group_id
  where m.token = kid_token;
$$;
revoke all on function public.kid_home(uuid) from public;
grant execute on function public.kid_home(uuid) to anon, authenticated;

-- One assigned book: clean pages (as for share links) plus this child's own work.
create or replace function public.kid_book(kid_token uuid, book uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'title', b.title,
    'trim_size', b.trim_size,
    'bleed', coalesce(to_jsonb(b) -> 'bleed', 'false'::jsonb),
    'pages', coalesce((
      select jsonb_agg(p - 'fillDataUrl' - 'completedAt' - 'thumbnailDataUrl' order by ord)
      from jsonb_array_elements(b.pages) with ordinality as e(p, ord)
      where not coalesce((p ->> 'isBlankBack')::boolean, false)
    ), '[]'::jsonb),
    'work', coalesce((
      select jsonb_object_agg(w.page_id, jsonb_build_object('fill', w.fill, 'thumb', w.thumb, 'completed_at', w.completed_at, 'sticker', w.sticker, 'comment', w.comment))
      from public.kid_work w where w.member_id = m.id and w.book_id = b.id
    ), '{}'::jsonb)
  )
  from public.kid_members m
  join public.kid_group_books gb on gb.group_id = m.group_id and gb.book_id = book
  join public.books b on b.id = gb.book_id
  where m.token = kid_token;
$$;
revoke all on function public.kid_book(uuid, uuid) from public;
grant execute on function public.kid_book(uuid, uuid) to anon, authenticated;

-- Saves one page of the child's coloring. Only for a book given to their
-- group, and only for a page that's really in it. A finished page stays
-- finished (its first completion time is kept).
create or replace function public.kid_save(kid_token uuid, book uuid, page text, page_fill text, page_thumb text, done boolean)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  me uuid;
begin
  select m.id into me
  from public.kid_members m
  join public.kid_group_books gb on gb.group_id = m.group_id and gb.book_id = book
  where m.token = kid_token;
  if me is null then
    return false;
  end if;
  if not exists (select 1 from public.books b, jsonb_array_elements(b.pages) p where b.id = book and p ->> 'id' = page) then
    return false;
  end if;
  insert into public.kid_work as w (member_id, book_id, page_id, fill, thumb, completed_at, updated_at)
  values (me, book, page, page_fill, page_thumb, case when done then now() end, now())
  on conflict (member_id, book_id, page_id) do update
    set fill = coalesce(excluded.fill, w.fill),
        thumb = coalesce(excluded.thumb, w.thumb),
        completed_at = coalesce(w.completed_at, excluded.completed_at),
        updated_at = now();
  return true;
end;
$$;
revoke all on function public.kid_save(uuid, uuid, text, text, text, boolean) from public;
grant execute on function public.kid_save(uuid, uuid, text, text, text, boolean) to anon, authenticated;

-- ===========================================================================
-- 11_book_members.sql
-- ===========================================================================

-- Working on a book together: the owner invites people with a link, as
-- editors (they change the book) or viewers (they read it and comment).
-- The book stays the owner's: nobody — owner included — can hand it to
-- another user_id (trigger below), and only the owner manages people.
--
-- Requires sql/00_books.sql and sql/02_page_comments.sql (it widens
-- can_review_book to members). Safe to re-run; run again after re-running 02.

create table if not exists public.book_members (
  book_id uuid not null references public.books (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'editor' check (role in ('editor', 'viewer')),
  email text,
  added_at timestamptz not null default now(),
  primary key (book_id, user_id)
);
create index if not exists book_members_user_idx on public.book_members (user_id);

create table if not exists public.book_invites (
  token uuid primary key default gen_random_uuid(),
  book_id uuid not null references public.books (id) on delete cascade,
  role text not null default 'editor' check (role in ('editor', 'viewer')),
  created_by uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create index if not exists book_invites_book_idx on public.book_invites (book_id);

-- 'owner' | 'editor' | 'viewer' | null for the signed-in user.
create or replace function public.book_role(target uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when exists (select 1 from public.books b where b.id = target and b.user_id = auth.uid()) then 'owner'
    else (select m.role from public.book_members m where m.book_id = target and m.user_id = auth.uid())
  end;
$$;
revoke all on function public.book_role(uuid) from public, anon;
grant execute on function public.book_role(uuid) to authenticated;

-- Books: members read, editors change. Additive to the owner's own policies.
drop policy if exists "Members read shared books" on public.books;
create policy "Members read shared books" on public.books
  for select to authenticated
  using ((select public.book_role(id)) in ('editor', 'viewer'));

drop policy if exists "Editors change shared books" on public.books;
create policy "Editors change shared books" on public.books
  for update to authenticated
  using ((select public.book_role(id)) = 'editor')
  with check ((select public.book_role(id)) = 'editor');

-- A book never changes hands — not by an editor, not by mistake.
create or replace function public.books_keep_owner() returns trigger
language plpgsql
as $$
begin
  if new.user_id is distinct from old.user_id then
    raise exception 'a book can''t be given to another account' using errcode = '42501';
  end if;
  return new;
end;
$$;
drop trigger if exists books_keep_owner on public.books;
create trigger books_keep_owner before update on public.books for each row execute function public.books_keep_owner();

alter table public.book_members enable row level security;
alter table public.book_invites enable row level security;
revoke all on public.book_members, public.book_invites from anon;

-- Everyone on a book sees who else is on it; the owner changes roles and
-- removes people; anyone can leave a book themselves.
grant select, delete on public.book_members to authenticated;
grant update (role) on public.book_members to authenticated;
drop policy if exists "See who's on the book" on public.book_members;
create policy "See who's on the book" on public.book_members for select to authenticated using ((select public.book_role(book_id)) is not null);
drop policy if exists "Owner changes roles" on public.book_members;
create policy "Owner changes roles" on public.book_members for update to authenticated using ((select public.book_role(book_id)) = 'owner') with check ((select public.book_role(book_id)) = 'owner');
drop policy if exists "Owner removes, members leave" on public.book_members;
create policy "Owner removes, members leave" on public.book_members for delete to authenticated using (user_id = auth.uid() or (select public.book_role(book_id)) = 'owner');

grant select, insert on public.book_invites to authenticated;
grant update (revoked_at) on public.book_invites to authenticated;
drop policy if exists "Owner manages invites" on public.book_invites;
create policy "Owner manages invites" on public.book_invites for all to authenticated
  using ((select public.book_role(book_id)) = 'owner')
  with check (created_by = auth.uid() and (select public.book_role(book_id)) = 'owner');

-- Opening an invite link while signed in: join the book (or change role to
-- the invite's). The invite stays usable for the rest of the team until
-- the owner turns it off. Returns the book id, or null for a dead link.
create or replace function public.accept_book_invite(invite uuid)
returns uuid
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  inv public.book_invites%rowtype;
  me uuid := auth.uid();
begin
  if me is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  select * into inv from public.book_invites where token = invite and revoked_at is null;
  if not found then
    return null;
  end if;
  if exists (select 1 from public.books b where b.id = inv.book_id and b.user_id = me) then
    return inv.book_id; -- the owner opening their own link
  end if;
  insert into public.book_members (book_id, user_id, role, email)
  values (inv.book_id, me, inv.role, (select u.email from auth.users u where u.id = me))
  on conflict (book_id, user_id) do update set role = excluded.role;
  return inv.book_id;
end;
$$;
revoke all on function public.accept_book_invite(uuid) from public, anon;
grant execute on function public.accept_book_invite(uuid) to authenticated;

-- "Shared with me" in the library: books I'm a member of, with my role.
create or replace function public.books_shared_with_me()
returns table (book jsonb, role text)
language sql
stable
security definer
set search_path = ''
as $$
  select to_jsonb(b), m.role
  from public.book_members m
  join public.books b on b.id = m.book_id
  where m.user_id = auth.uid()
  order by b.updated_at desc;
$$;
revoke all on function public.books_shared_with_me() from public, anon;
grant execute on function public.books_shared_with_me() to authenticated;

-- Comments: members of a book read and write them too (widens sql/02).
create or replace function public.can_review_book(target_book text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_admin()
      or exists (select 1 from public.books b where b.id::text = target_book and b.user_id = auth.uid())
      or exists (select 1 from public.book_members m where m.book_id::text = target_book and m.user_id = auth.uid());
$$;
revoke all on function public.can_review_book(text) from public, anon;
grant execute on function public.can_review_book(text) to authenticated;

-- ===========================================================================
-- 12_app_errors.sql
-- ===========================================================================

-- Error log without a third-party service: server errors (instrumentation.ts)
-- and browser errors (instrumentation-client.ts → /api/log-error) land
-- here, the same error folded into one row with a count, and supervisors
-- read them on /studio/admin.
--
-- Requires sql/01_admin_role.sql (is_admin). Safe to re-run.

create table if not exists public.app_errors (
  id bigint generated always as identity primary key,
  source text not null check (source in ('server', 'client')),
  message text not null,
  path text not null default '',
  digest text,
  user_agent text,
  first_at timestamptz not null default now(),
  last_at timestamptz not null default now(),
  hits int not null default 1,
  unique (source, message, path)
);
create index if not exists app_errors_last_idx on public.app_errors (last_at desc);
alter table public.app_errors enable row level security;
revoke all on public.app_errors from anon, authenticated;

-- The only way in: bounded fields, one row per distinct error (a storm of
-- the same error is one row with a high count, not a full table).
create or replace function public.log_app_error(error_source text, error_message text, error_path text default '', error_digest text default null, error_agent text default null)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if error_source not in ('server', 'client') or coalesce(trim(error_message), '') = '' then
    return;
  end if;
  insert into public.app_errors as e (source, message, path, digest, user_agent)
  values (error_source, left(error_message, 500), left(coalesce(error_path, ''), 300), left(error_digest, 100), left(error_agent, 300))
  on conflict (source, message, path) do update
    set hits = e.hits + 1, last_at = now(), digest = coalesce(excluded.digest, e.digest), user_agent = coalesce(excluded.user_agent, e.user_agent);
end;
$$;
revoke all on function public.log_app_error(text, text, text, text, text) from public;
grant execute on function public.log_app_error(text, text, text, text, text) to anon, authenticated;

create or replace function public.admin_recent_errors(max_rows int default 50)
returns setof public.app_errors
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query select * from public.app_errors order by last_at desc limit least(greatest(max_rows, 1), 200);
end;
$$;
revoke all on function public.admin_recent_errors(int) from public, anon;
grant execute on function public.admin_recent_errors(int) to authenticated;

-- Supervisors clear an error once it's fixed.
create or replace function public.admin_clear_error(error_id bigint)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  delete from public.app_errors where id = error_id;
end;
$$;
revoke all on function public.admin_clear_error(bigint) from public, anon;
grant execute on function public.admin_clear_error(bigint) to authenticated;
